services:
  postgres:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_USER: wonki
      POSTGRES_PASSWORD: nofoodwaste 
      POSTGRES_DB: wonki_db
    ports:
      - "5432:5432"
    # volumes:
    #   - ./data/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


